# Generated by Django 2.2.3 on 2019-12-09 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20191209_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_num_size',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True, validators=[django.core.validators.MaxValueValidator(45), django.core.validators.MinValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='subcategories_name',
            field=models.CharField(max_length=40),
        ),
    ]
